-- ============================================================
-- SIEMBRA — Encuesta ANOVA Research: caracterización y experiencia
-- de atención en salud, población afrodescendiente Región de Los Ríos
-- ============================================================
-- Corre esto en Supabase → SQL Editor DESPUÉS de migracion-logica-condicional.sql
-- Crea la encuesta con marca ANOVA y las 20 preguntas con toda su lógica
-- (saltos, cascadas, condicionales, matriz) ya configurada.

insert into encuestas
  (id, titulo, descripcion, logo_url, banner_url, color_primario, mostrar_identificacion, texto_consentimiento)
values
  ('43eedf11-fa65-4f6b-8ceb-0138a24f7dd5', 'Encuesta de caracterización y experiencia usuaria — Población afrodescendiente',
   'Encuesta de caracterización y experiencia de atención en salud de la población afrodescendiente de la Región de Los Ríos.', 'assets/logo-anova.png', 'assets/banner-anova.png',
   '#2E5FD9', true, 'Usted está siendo invitado(a) a participar en una encuesta cuyo objetivo es conocer las características, experiencias y opiniones de personas afrodescendientes respecto de la atención recibida en establecimientos de salud de la Región de Los Ríos. Su participación es voluntaria y la encuesta tiene una duración aproximada de 10 minutos. La información proporcionada será utilizada exclusivamente con fines de investigación y análisis. Las respuestas serán analizadas de manera general y agregada; en ningún caso los resultados permitirán identificarla(o) individualmente ni asociar sus respuestas con su identidad. Puede decidir no participar, no responder alguna pregunta o finalizar la encuesta en cualquier momento, sin ninguna consecuencia para usted.');

insert into preguntas
  (id, encuesta_id, categoria, texto, tipo, opciones, orden, otro_trigger,
   mostrar_si, salta_a, opciones_por, matriz_filas, escala_min, escala_max,
   escala_min_label, escala_max_label, requerida)
values
  ('9e79131c-63c7-4d69-94a8-55a4eaae9d72', '43eedf11-fa65-4f6b-8ceb-0138a24f7dd5', 'Consentimiento informado', '¿Ha leído y comprendido esta información y acepta participar voluntariamente en esta encuesta?', 'opcion_unica', '["Sí, acepto participar", "No, no acepto participar"]'::jsonb, 0, null, null, '{"valores": ["No, no acepto participar"], "destino_categoria": "FIN"}'::jsonb, null, null, null, null, null, null, true),
  ('f6daea97-9a20-4380-9e33-72b0e3f4a317', '43eedf11-fa65-4f6b-8ceb-0138a24f7dd5', 'Identificación étnica', '¿Se considera usted afrodescendiente?', 'opcion_unica', '["Sí", "No", "No sabe / no está seguro(a)", "Prefiere no responder"]'::jsonb, 1, null, null, null, null, null, null, null, null, null, true),
  ('4a191734-575b-4c75-ad3b-5dfcd997db8b', '43eedf11-fa65-4f6b-8ceb-0138a24f7dd5', 'Perfil del encuestado', 'Para clasificar sus respuestas con las de otras personas, indíquenos su género.', 'opcion_unica', '["Hombre", "Mujer"]'::jsonb, 2, null, null, null, null, null, null, null, null, null, true),
  ('7ee7fb39-2db2-48f9-abd3-68fd4a1b00e4', '43eedf11-fa65-4f6b-8ceb-0138a24f7dd5', 'Perfil del encuestado', '¿Cuál es su fecha de nacimiento?', 'fecha', '[]'::jsonb, 3, null, null, null, null, null, null, null, null, null, true),
  ('495c4c29-2f72-43ad-a891-7886d6376e14', '43eedf11-fa65-4f6b-8ceb-0138a24f7dd5', 'Perfil del encuestado', '¿Cuál es su región de residencia?', 'opcion_unica', '["Región de Los Ríos", "Región de La Araucanía", "Región de Los Lagos", "Otra"]'::jsonb, 4, 'Otra', null, null, null, null, null, null, null, null, true),
  ('4c72580d-9f96-4d1f-8233-7d2471a73abd', '43eedf11-fa65-4f6b-8ceb-0138a24f7dd5', 'Perfil del encuestado', '¿Cuál es su comuna de residencia?', 'opcion_unica', '[]'::jsonb, 5, 'Otra', '{"pregunta_id": "495c4c29-2f72-43ad-a891-7886d6376e14", "valores": ["Región de Los Ríos", "Región de La Araucanía", "Región de Los Lagos"]}'::jsonb, null, '{"pregunta_id": "495c4c29-2f72-43ad-a891-7886d6376e14", "mapa": {"Región de Los Ríos": ["Corral", "Futrono", "La Unión", "Lago Ranco", "Lanco", "Los Lagos", "Máfil", "Mariquina", "Paillaco", "Panguipulli", "Río Bueno", "Valdivia", "Otra"], "Región de La Araucanía": ["Angol", "Carahue", "Cholchol", "Collipulli", "Cunco", "Curacautín", "Curarrehue", "Ercilla", "Freire", "Galvarino", "Gorbea", "Lautaro", "Loncoche", "Lonquimay", "Los Sauces", "Lumaco", "Melipeuco", "Nueva Imperial", "Padre Las Casas", "Perquenco", "Pitrufquén", "Pucón", "Purén", "Renaico", "Saavedra", "Temuco", "Teodoro Schmidt", "Toltén", "Traiguén", "Victoria", "Vilcún", "Villarrica"], "Región de Los Lagos": ["Ancud", "Calbuco", "Castro", "Chaitén", "Chonchi", "Cochamó", "Curaco de Vélez", "Dalcahue", "Fresia", "Frutillar", "Futaleufú", "Hualaihué", "Llanquihue", "Los Muermos", "Maullín", "Osorno", "Palena", "Puerto Montt", "Puerto Octay", "Puerto Varas", "Puqueldón", "Purranque", "Puyehue", "Queilén", "Quellón", "Quemchi", "Quinchao", "Río Negro", "San Pablo"]}}'::jsonb, null, null, null, null, null, true),
  ('32a06d71-b6f3-4606-a931-df9813049523', '43eedf11-fa65-4f6b-8ceb-0138a24f7dd5', 'Perfil del encuestado', '¿Su nacionalidad es…?', 'opcion_unica', '["Chilena", "Venezolana", "Haitiana", "Peruana", "Colombiana", "Boliviana", "Argentina", "Brasileña", "Otra"]'::jsonb, 6, 'Otra', null, null, null, null, null, null, null, null, true),
  ('e147cfee-a997-440f-a5c0-c1152b33f466', '43eedf11-fa65-4f6b-8ceb-0138a24f7dd5', 'Perfil del encuestado', '¿Cuál es el nivel educacional más alto que ha completado?', 'opcion_unica', '["Educación primaria incompleta", "Educación primaria completa", "Educación secundaria incompleta", "Educación secundaria completa", "Educación superior técnica incompleta", "Educación superior técnica completa", "Educación universitaria incompleta", "Educación universitaria completa", "Estudios de posgrado incompletos", "Estudios de posgrado completos", "Prefiere no responder"]'::jsonb, 7, null, null, null, null, null, null, null, null, null, true),
  ('121dc12e-14f6-441d-a525-0655ced1f4db', '43eedf11-fa65-4f6b-8ceb-0138a24f7dd5', 'Perfil del encuestado', '¿Cuál es su actividad principal?', 'opcion_unica', '["Trabaja", "Estudia", "Realiza labores del hogar", "Jubilado, pensionado", "Buscando trabajo", "Prefiere no responder", "Otro"]'::jsonb, 8, 'Otro', null, null, null, null, null, null, null, null, true),
  ('fbcacb67-99c3-44ef-aa3c-aa88ea502c39', '43eedf11-fa65-4f6b-8ceb-0138a24f7dd5', 'Perfil del encuestado', 'Si trabaja, ¿cuál es su rango de ingresos?', 'opcion_unica', '["Menos de $350.000", "Entre $350.001 - $550.000", "Entre $550.001 - $800.000", "Entre $801.001 - $1.200.000", "Entre $1.200.001 - $1.800.000", "Entre $1.800.001 - $2.500.000", "Entre $2.500.001 - $4.000.000", "Más de $4.000.000", "Prefiero no responder"]'::jsonb, 9, null, '{"pregunta_id": "121dc12e-14f6-441d-a525-0655ced1f4db", "valores": ["Trabaja"]}'::jsonb, null, null, null, null, null, null, null, true),
  ('e72a19a5-9a61-4125-9f19-b76233a6fff9', '43eedf11-fa65-4f6b-8ceb-0138a24f7dd5', 'Perfil del encuestado', '¿Tiene hijos/as o personas a su cargo?', 'opcion_unica', '["Sí", "No"]'::jsonb, 10, null, null, null, null, null, null, null, null, null, true),
  ('bbf146c3-2581-4234-8f93-b8718982ca34', '43eedf11-fa65-4f6b-8ceb-0138a24f7dd5', 'Acceso a atención en salud', '¿Se atiende o ha recibido atención en algún centro de salud de la Región de Los Ríos?', 'opcion_unica', '["Sí", "No", "No sabe / no recuerda", "Prefiere no responder"]'::jsonb, 11, null, null, '{"valores": ["No", "No sabe / no recuerda", "Prefiere no responder"], "destino_categoria": "Cierre"}'::jsonb, null, null, null, null, null, null, true),
  ('82385e71-c0d3-4c0f-8ecd-785d46b09ff5', '43eedf11-fa65-4f6b-8ceb-0138a24f7dd5', 'Atención en centros de salud', 'Generalmente, ¿a qué acude cuando se atiende en un centro de salud de la Región de Los Ríos?', 'multiple', '["Consultas de medicina general", "Consultas con médicos especialistas", "Atención de urgencia", "Exámenes médicos o de laboratorio", "Procedimientos o tratamientos", "Controles de salud", "Atención de salud mental", "Atención odontológica", "Atención relacionada con embarazo, parto o salud sexual y reproductiva", "Retiro o solicitud de medicamentos", "Vacunación", "Rehabilitación o kinesiología", "Otra"]'::jsonb, 12, 'Otra', null, null, null, null, null, null, null, null, true),
  ('9d988fa2-2860-4d9a-98c9-d1a55679b55d', '43eedf11-fa65-4f6b-8ceb-0138a24f7dd5', 'Atención en centros de salud', '¿Con qué frecuencia se atiende en centros de salud de la Región de Los Ríos?', 'opcion_unica', '["Varias veces al mes", "Una vez al mes", "Cada 2 o 3 meses", "Cada 4 a 6 meses", "Una vez al año", "Menos de una vez al año", "No recuerda", "Prefiere no responder"]'::jsonb, 13, null, null, null, null, null, null, null, null, null, true),
  ('98b15abc-3d2f-406e-bfa9-697038053c87', '43eedf11-fa65-4f6b-8ceb-0138a24f7dd5', 'Atención en centros de salud', '¿En qué tipo de establecimiento de salud se atiende con mayor frecuencia?', 'opcion_unica', '["Hospital público", "CESFAM", "CECOSF", "Posta o estación médico-rural", "Clínica privada", "Centro médico privado", "Otro", "No sabe / no recuerda"]'::jsonb, 14, 'Otro', null, null, null, null, null, null, null, null, true),
  ('ed0571a7-6311-4834-8ee7-cf705e85ca6d', '43eedf11-fa65-4f6b-8ceb-0138a24f7dd5', 'Atención en centros de salud', '¿En cuál de los siguientes establecimientos de salud se atiende habitualmente?', 'opcion_unica', '[]'::jsonb, 15, '["Otro hospital público", "Otro CESFAM", "Otra clínica privada", "Otro centro médico privado"]'::jsonb, null, null, '{"pregunta_id": "98b15abc-3d2f-406e-bfa9-697038053c87", "mapa": {"Hospital público": ["Hospital Base Valdivia", "Hospital Juan Morey de La Unión", "Hospital de Río Bueno", "Hospital de Paillaco", "Hospital de Los Lagos", "Hospital de Lanco", "Hospital de Corral", "Hospital Santa Elisa de Mariquina", "Hospital Padre Bernabé de Lucerna de Panguipulli", "Otro hospital público", "No sabe / no recuerda"], "CESFAM": ["CESFAM Externo de Valdivia", "CESFAM Angachilla", "CESFAM Dr. Jorge Sabat", "CESFAM Las Ánimas", "CESFAM Niebla", "CESFAM de Corral", "CESFAM de Lanco", "CESFAM Malalhue", "CESFAM de Los Lagos", "CESFAM de Máfil", "CESFAM de Mariquina", "CESFAM de Paillaco", "CESFAM de Panguipulli", "CESFAM de La Unión", "CESFAM de Río Bueno", "CESFAM de Futrono", "CESFAM de Lago Ranco", "Otro CESFAM", "No sabe / no recuerda"], "CECOSF": "__texto__", "Posta o estación médico-rural": "__texto__", "Clínica privada": ["Clínica Alemana de Valdivia", "Otra clínica privada", "No sabe / no recuerda"], "Centro médico privado": ["RedSalud Valdivia", "Otro centro médico privado", "No sabe / no recuerda"], "Otro": "__texto__"}}'::jsonb, null, null, null, null, null, false),
  ('f20ae587-a443-4359-836d-5a5ccc00579f', '43eedf11-fa65-4f6b-8ceb-0138a24f7dd5', 'Experiencia y satisfacción usuaria', 'Pensando en su experiencia más reciente, ¿qué tan satisfecho(a) quedó con la atención recibida?', 'opcion_unica', '["Muy satisfecho", "Satisfecho", "Ni satisfecho ni insatisfecho", "Insatisfecho", "Muy insatisfecho", "No sabe / no recuerda", "Prefiere no responder"]'::jsonb, 16, null, null, null, null, null, null, null, null, null, true),
  ('c963864f-bd45-4092-8065-8ceeb6d7a106', '43eedf11-fa65-4f6b-8ceb-0138a24f7dd5', 'Experiencia y satisfacción usuaria', 'Considerando una escala del 1 al 5, ¿qué tan satisfecho(a) está con los siguientes aspectos de la atención recibida?', 'matriz', '["Muy satisfecho", "Satisfecho", "Ni satisfecho ni insatisfecho", "Insatisfecho", "Muy insatisfecho"]'::jsonb, 17, null, null, null, null, '["Calidad de la atención", "Trato recibido por el personal", "Tiempo de espera", "Facilidad para acceder a la atención", "Información recibida sobre su atención", "Resolución de su necesidad de atención"]'::jsonb, null, null, null, null, true),
  ('e2c39d2a-5971-4f55-9b72-a7e1386de20e', '43eedf11-fa65-4f6b-8ceb-0138a24f7dd5', 'Experiencia y satisfacción usuaria', '¿Qué tan probable es que recomiende el centro de salud donde se atiende habitualmente a un familiar o amigo?', 'escala', '[]'::jsonb, 18, null, null, null, null, null, 1, 5, 'Nada probable', 'Muy probable', true),
  ('d82a670d-fa12-4c52-a2bd-46bb4fc69773', '43eedf11-fa65-4f6b-8ceb-0138a24f7dd5', 'Experiencia y satisfacción usuaria', 'Considerando todos los aspectos de la atención, ¿cómo evaluaría en general el servicio recibido en el centro de salud donde se atiende habitualmente?', 'opcion_unica', '["Muy malo", "Malo", "Regular", "Bueno", "Muy bueno", "No sabe / no recuerda", "Prefiere no responder"]'::jsonb, 19, null, null, null, null, null, null, null, null, null, true),
  ('5e679edc-2071-433c-a0a2-67d39281f1aa', '43eedf11-fa65-4f6b-8ceb-0138a24f7dd5', 'Experiencia y satisfacción usuaria', 'Pensando en su experiencia de atención en salud, ¿alguna vez ha sentido que ha recibido un trato diferente, injusto o discriminatorio debido a su origen, color de piel, nacionalidad, cultura u otro?', 'opcion_unica', '["Sí", "No", "No sabe / no recuerda", "Prefiere no responder"]'::jsonb, 20, null, null, null, null, null, null, null, null, null, true),
  ('23bc764f-209c-4baf-9dc1-dbddbd262406', '43eedf11-fa65-4f6b-8ceb-0138a24f7dd5', 'Experiencia y satisfacción usuaria', '¿Cuál fue el motivo o la situación que generó este trato diferente, injusto o discriminatorio?', 'multiple', '["Por mi color de piel o apariencia física", "Por mi origen o ascendencia", "Por mi identidad afrodescendiente", "Por mi nacionalidad", "Por mi forma de hablar o acento", "Por mi cultura o costumbres", "Otra razón", "No sabe / no recuerda", "Prefiere no responder"]'::jsonb, 21, 'Otra razón', '{"pregunta_id": "5e679edc-2071-433c-a0a2-67d39281f1aa", "valores": ["Sí"]}'::jsonb, null, null, null, null, null, null, null, true),
  ('f047d051-330f-4771-b619-d705dff15927', '43eedf11-fa65-4f6b-8ceb-0138a24f7dd5', 'Cierre', '¿Hay algún aspecto de la atención en el centro de salud que considere que debería mejorar?', 'texto_largo', '[]'::jsonb, 22, null, null, null, null, null, null, null, null, null, false);

-- link público de esta encuesta una vez corrido este script:
-- https://encuestapp-two.vercel.app/?e=43eedf11-fa65-4f6b-8ceb-0138a24f7dd5