-- ------------------------------------------------------------------
-- Este archivo quedó solo como recordatorio de los pasos manuales
-- (las políticas de "leer respuestas autenticado" ahora están en
-- supabase-setup.sql junto con el resto del esquema).
--
-- PASOS MANUALES QUE FALTAN (se hacen desde el dashboard, no por SQL):
--
-- 1. Ve a Authentication → Sign In / Providers → Email
--    y desactiva "Allow new users to sign up".
--    Esto evita que cualquier persona con solo escribir su correo
--    pueda crearse una cuenta y entrar al panel.
--
-- 2. Ve a Authentication → Users → "Add user" → "Invite user"
--    y agrega ahí el email de tu cliente (ej: jrgvegal@gmail.com).
--    Solo los emails que invites ahí van a poder pedir el magic link
--    y entrar al panel.
--
-- 3. Ve a Authentication → URL Configuration → "Redirect URLs"
--    y agrega la URL de tu panel una vez deployado, por ejemplo:
--    https://encuestapp-two.vercel.app/panel/
-- ------------------------------------------------------------------
